---
title: "Advent Appraisal 2024 - Fortnum & Mason"
output: 
 flexdashboard::flex_dashboard:
  theme:
      version: 4
      bg: "#FFFFFF"
      fg: "#FFFFFF" 
      primary: "#B91F1C"
      navbar-bg: "#B91F1C"
  orientation: rows
  vertical_layout: fill
  horizontal_layout: fill
---
 
```{r setup, include = FALSE}

source("./R/data-ingest.R")

```

Tea
=================================================================

Row {data-height = 100}
------------------------------------------------------------------

### Best Tea Name {.value-box}

```{r}

valueBox(value = filter(advent_averages, tea_score == max(tea_score, na.rm = TRUE)) %>% 
          pull(tea_name) %>%
          unique() %>% 
          paste(collapse = ", "))

```

### Best Tea Score {.value-box}

```{r}

valueBox(value = filter(advent_averages, tea_score == max(tea_score, na.rm = TRUE)) %>% 
          pull(tea_score) %>%
          round(digits = 1) %>%
          unique() %>% 
          paste(collapse = ", ")) 
  
```

### Avg Tea Score {.value-box}

```{r}

valueBox(value =  summarise(advent_averages, 
           average_tea_score = mean(tea_score, na.rm = TRUE)) %>% 
  pull() %>% 
  round(digits = 1))

```

Row {data-height = 400}
------------------------------------------------------------------

### Tea Plot

```{r}

tea_plot

```

### Tea - Closest Scores

```{r}

tea_close_score_plot %>% 
  layout(hovermode = "y unified")

```


Biscuit
=================================================================

Row {data-height = 100}
------------------------------------------------------------------

### Best Biscuit Name {.value-box}

```{r}

valueBox(value = filter(advent_averages, biscuit_score == max(biscuit_score, na.rm = TRUE)) %>% 
          pull(biscuit_name))

```

### Best Biscuit Score {.value-box}

```{r}

valueBox(value = filter(advent_averages, biscuit_score == max(biscuit_score, na.rm = TRUE)) %>% 
          pull(biscuit_score) %>%
          round(digits = 1) %>% 
          cat(sep = ", ")) 
  
```

### Avg Biscuit Score {.value-box}

```{r}

valueBox(value =  summarise(advent_averages, 
           average_biscuit_score = mean(biscuit_score, na.rm = TRUE)) %>% 
  pull() %>% 
  round(digits = 1))

```

Row {data-height = 400}
------------------------------------------------------------------

### Biscuit Plot

```{r}

biscuit_plot

```

### Biscuit - Closest Scores

```{r}

biscuit_close_score_plot %>% 
  layout(hovermode = "y unified")

```

Pairing
=================================================================

Row {data-height = 100}
------------------------------------------------------------------

### Best Pairing Name {.value-box}

```{r}

valueBox(filter(advent_averages, pairing_score == max(pairing_score, na.rm = TRUE)) %>% 
          mutate(pairing_name = paste(tea_name, biscuit_name, sep = " & ")) %>% 
          pull(pairing_name) %>% 
          paste(collapse = ", "))

```

### Best Pairing Score {.value-box}

```{r}

valueBox(value = filter(advent_averages, pairing_score == max(pairing_score, na.rm = TRUE)) %>% 
          pull(pairing_score) %>% 
          cat(sep = ", ")) 
  
```

### Avg Pairing Score {.value-box}

```{r}

valueBox(value =  summarise(advent_averages, 
           average_tea_score = mean(tea_score, na.rm = TRUE)) %>% 
  pull() %>% 
  round(digits = 1))

```

Row {data-height = 400}
------------------------------------------------------------------

### Pairing Plot

```{r}

combination_plot

```

### Pairing - Closest Scores

```{r}

combination_close_score_plot %>% 
  layout(hovermode = "y unified")

```
